services:
  - type: web
    name: stakewise-frontend
    env: static
    buildCommand: yarn --frozen-lockfile install; yarn build
    staticPublishPath: ./dist
    headers:
      - path: /*
        headers:
          - key: X-Frame-Options
            value: DENY
          - key: X-Content-Type-Options
            value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
